import imagePlaceHolder from "./public/assets/image_place_holder.png";
import avatarPlaceHolder from "./public/assets/Avatar.png";

const data = {
  Popular: [
    {
      id: "1",
      title: "Title 1P",
      userName: "Alhassan  Ali",
      cardCount: "3000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis ligula nec tellus pellentesque, eu tristique justo sodales.",
      setId: "2",
      userId: "3",
    },
    {
      id: "2",
      title: "Title 2P",
      userName: "Lana Kamal",
      cardCount: "4000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["Learn", "Learning", "English", "English"],
      description:
        "Phasellus imperdiet pharetra sapien sed mollis. Fusce tempor lacus at nibh pulvinar egestas. Donec suscipit gravida ipsum sit amet facilisis.",
      setId: "3",
      userId: "4",
    },
    {
      id: "3",
      title: "Title 3P",
      userName: "Muhammad Burhan",
      cardCount: "5000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Exam", "English", "English"],
      description:
        "Nunc ac erat id augue tristique vehicula. Aliquam in blandit tellus. Cras imperdiet lorem ante, vel imperdiet odio auctor et. Maecenas ligula dui, pellentesque nec eros in, semper ultrices justo. Donec blandit orci massa, ac faucibus magna volutpat ut.",
      setId: "4",
      userId: "5",
    },
    {
      id: "4",
      title: "Title 4P",
      userName: "Ulfet Adnan",
      cardCount: "6000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "Math", "English"],
      description:
        "Quisque et justo et dolor ullamcorper tristique. Donec dolor libero, placerat at hendrerit sed, tristique sit amet ligula. Duis eu semper felis, sit amet suscipit risus.",
      setId: "5",
      userId: "6",
    },
    {
      id: "5",
      title: "Title 5P",
      userName: "Yasser Muayed",
      cardCount: "7000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "Test"],
      description:
        "Vestibulum fringilla suscipit nisl, quis auctor odio blandit non. Donec sapien dui, porta ut dapibus et, egestas et est. Morbi tellus mauris, iaculis ut ullamcorper et, ullamcorper eu enim.",
      setId: "6",
      userId: "7",
    },
  ],
  Latest: [
    {
      id: "1",
      title: "Title 1L",
      userName: "Alhassan  Ali",
      cardCount: "3000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis ligula nec tellus pellentesque, eu tristique justo sodales.",
      setId: "2",
      userId: "3",
    },
    {
      id: "2",
      title: "Title 2L",
      userName: "Lana Kamal",
      cardCount: "4000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Phasellus imperdiet pharetra sapien sed mollis. Fusce tempor lacus at nibh pulvinar egestas. Donec suscipit gravida ipsum sit amet facilisis.",
      setId: "3",
      userId: "4",
    },
    {
      id: "3",
      title: "Title 3L",
      userName: "Muhammad Burhan",
      cardCount: "5000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Nunc ac erat id augue tristique vehicula. Aliquam in blandit tellus. Cras imperdiet lorem ante, vel imperdiet odio auctor et. Maecenas ligula dui, pellentesque nec eros in, semper ultrices justo. Donec blandit orci massa, ac faucibus magna volutpat ut.",
      setId: "4",
      userId: "5",
    },
    {
      id: "4",
      title: "Title 4L",
      userName: "Ulfet Adnan",
      cardCount: "6000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Quisque et justo et dolor ullamcorper tristique. Donec dolor libero, placerat at hendrerit sed, tristique sit amet ligula. Duis eu semper felis, sit amet suscipit risus.",
      setId: "5",
      userId: "6",
    },
    {
      id: "5",
      title: "Title 5L",
      userName: "Yasser Muayed",
      cardCount: "7000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Vestibulum fringilla suscipit nisl, quis auctor odio blandit non. Donec sapien dui, porta ut dapibus et, egestas et est. Morbi tellus mauris, iaculis ut ullamcorper et, ullamcorper eu enim.",
      setId: "6",
      userId: "7",
    },
  ],
  Suggested: [
    {
      id: "1",
      title: "Title 1S",
      userName: "Alhassan  Ali",
      cardCount: "3000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis ligula nec tellus pellentesque, eu tristique justo sodales.",
      setId: "2",
      userId: "3",
    },
    {
      id: "2",
      title: "Title 2S",
      userName: "Lana Kamal",
      cardCount: "4000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Phasellus imperdiet pharetra sapien sed mollis. Fusce tempor lacus at nibh pulvinar egestas. Donec suscipit gravida ipsum sit amet facilisis.",
      setId: "3",
      userId: "4",
    },
    {
      id: "3",
      title: "Title 3S",
      userName: "Muhammad Burhan",
      cardCount: "5000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Nunc ac erat id augue tristique vehicula. Aliquam in blandit tellus. Cras imperdiet lorem ante, vel imperdiet odio auctor et. Maecenas ligula dui, pellentesque nec eros in, semper ultrices justo. Donec blandit orci massa, ac faucibus magna volutpat ut.",
      setId: "4",
      userId: "5",
    },
    {
      id: "4",
      title: "Title 4S",
      userName: "Ulfet Adnan",
      cardCount: "6000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Quisque et justo et dolor ullamcorper tristique. Donec dolor libero, placerat at hendrerit sed, tristique sit amet ligula. Duis eu semper felis, sit amet suscipit risus.",
      setId: "5",
      userId: "6",
    },
    {
      id: "5",
      title: "Title 5S",
      userName: "Yasser Muayed",
      cardCount: "7000",
      imageUrl: imagePlaceHolder,
      avatar: avatarPlaceHolder,
      tags: ["English", "Learning", "English", "English"],
      description:
        "Vestibulum fringilla suscipit nisl, quis auctor odio blandit non. Donec sapien dui, porta ut dapibus et, egestas et est. Morbi tellus mauris, iaculis ut ullamcorper et, ullamcorper eu enim.",
      setId: "6",
      userId: "7",
    },
  ],
  top_categories: [
    {
      id: "1",
      name: "Math",
      categories: ["Algebra", "Arithmetic", "Geometry"],
    },
    {
      id: "2",
      name: "Programming",
      categories: ["React", "Java", "Node"],
    },
    {
      id: "3",
      name: "Language",
      categories: ["Japanese", "English", "Italin"],
    },
  ],
};
export default data;
